version: '3'

services:
  payment-manager-api:
    image: bohdanbulakh/payment-manager-api:lab2
    container_name: payment-manager-api-lab2
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - watchtower
    ports:
      - "${PUBLIC_API_PORT}:${PORT}"
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--cleanup"
      - "-i"
      - "60"
